### ISSUE TITLE
Make #ifdefs only relevant to i controlled by a flag

### ISSUE THREAD

**Issue by NattyNarwhal** [MonoOni/binarydist#15]
This would clarify intent for what's needed for i vs. AIX; and lets us build a marginally better build for AIX.

This would likely consist of considering `_AIX` defines to say, `__PASE__`. Because i tooling is the same as AIX and thus won't have a flag; and since we cross-compile from AIX anyway, we'd have to pass a flag manually - but adding `-D__PASE__` to `./configure` is no problem.

**Comment by kadler** [comment]
FYI, the GCC compilers that we ship with yum define `__PASE__` automatically

**Comment by NattyNarwhal** [comment]
Ah, I'll have to switch definitions over to that - when I was doing the initial bringup on i, Perzl and Bull's toolchains didn't define that (being for AIX) and I wasn't aware of the new IBM toolchain.

**Comment by kadler** [comment]
Right. We're still shipping a modified & repackaged AIX toolbox GCC version, but we modified the GCC specs file to add `-D__PASE__`. You could so yourself as well. `gcc --dumpspecs > specs`, modify specs, move it next to libgcc_s.a under /opt/freeware/lib/gcc/... Or just define it in the `CPPFLAGS` passed to configure.

**Comment by NattyNarwhal** [comment]
Upstream merged said changes; so fixed.
