### ISSUE TITLE
Extend P/Invoke dlopen code to fudge guesses for AIX libraries

### ISSUE THREAD

**Issue by NattyNarwhal** [MonoOni/binarydist#16]
The library loader will try suffixes -  depending on platform, it will guess DLL for Windows, `dylib` for Mac OS, and `so` for any other Unix. While libraries on AIX could end in `so`, they're more likely to be encased in an archive. As such, the library loader should be extended to deal with AIX by trying these combinations, when given a library with no suffix and no DllMap entry:

* `libexample.so`
* `libexample.a(libexample.so)` (this requires a sprintf instead of just appending; but this is generally how autotools sets up built libraries...)
* `libexample.a(shr_64.so)` (when build as PPC64 like we are)
* `libexample.a(shr.so)`

**Comment by kadler** [comment]
FYI, we try to use the format defined in autotools with `--with-aix-soname=svr4`: `libfoo.so.1(shr_64.o)` with a symlink of `libfoo.so` pointing at it and a shr_64.imp that specifies the name `libfoo.so.1(shr_64.o)` name. You can read more about the configure option here: http://lists.gnu.org/archive/html/libtool/2011-01/msg00023.html

The only change you'd have to make to make this work is just always try to append `(shr_64.o)` to the name given and not check if it's .so or .a.
