### ISSUE TITLE
Dependent module libmonosgen-2.0.a could not be loaded

### ISSUE THREAD

**Issue by mlitters** [MonoOni/binarydist#31]
I want to try out this great Port but when I follow the instructions and make a "mcs hello.cs" I always get the error "Could not load program /opt/mono/bin/mono: Dependent module libmonosgen-2.0.a (libmonosgen-2.0.so.1) could not be loaded. Could not load module libmonosgen-2.0.a (libmonosgen-2.0.so.1). System error: No such file or directory."
When I look into the mono/lib directory there is a "libmonosgen-2.0.a" and I also put all the directories into my PATH Variable so the system should find it.

**Comment by NattyNarwhal** [comment]
Can you try running Mono with the environment variable `LIBPATH` set to `/opt/mono/lib:$LIBPATH`? Like so: `LIBPATH=/opt/mono/lib:$LIBPATH /opt/mono/bin/mono […]`. (Or in this case, mcs)

**Comment by mlitters** [comment]
I tried that and it brings the same error...

**Comment by mlitters** [comment]
I got it - with LIBPATH=/QOpenSys/opt/mono/lib:$LIBPATH and an export LIBPATH, he finaly finds the lib. Now he says he can't find the mscorlib.dll.
He looks in "/opt/mono/lib/mono/4.5/mscorlib.dll" but it is there....

**Comment by NattyNarwhal** [comment]
It almost sounds like `/` redirection to `/QOpenSys` doesn't seem to be working right. I don't recall off hand what settings could be affecting that. I'll look into it though.

**Comment by NattyNarwhal** [comment]
Can you get me a list of exported environment variables, either by the `env` or `export` commands in PASE? It looks like at least [one environment variable](https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_71/apis/pase_environ.htm) could influence behaviour of QOpenSys.

**Comment by mlitters** [comment]
I played a little bit (I am not familiar with Mono yet...) and set the MONO_PATH but now he says the mcs.exe cannot be found in the mono/4.5 directory...
Here is the environment Variables:
PATH=/QOpenSys/opt/mono/bin:/opt/mono/bin:/QOpenSys/pkgs/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin

**Comment by NattyNarwhal** [comment]
That doesn't seem complete; if I run `env` on a V7R3 system, I get:

```
$ env
_=/QOpenSys/usr/bin/env
LOGNAME=calvin
HOME=/home/Calvin
SSH_TTY=/dev/pts/0
MAIL=/var/spool/mail/calvin
PATH=/QOpenSys/opt/mono/bin:/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin
SSH_CLIENT=(redacted)
TZ=<EST>5<EDT>,M3.2.0,M11.1.0
SHELL=/home/Calvin/bin/oksh
TERM=xterm
LOGIN=calvin
SSH_CONNECTION=(redacted)
USER=calvin
```

**Comment by mlitters** [comment]
Yes - I only sent you the PATH Variable...
I don't think that the others really matters.
Maybe the Shell
Shell=/QOpenSys/usr/bin/bsh

**Comment by NattyNarwhal** [comment]
I was wondering if the `PASE_EXEC_QOPENSYS` variable may have been set. I guess if you didn't include it, it wasn't there.

Is the `/opt` symlink pointing to `/QOpenSys/opt`? Do `ls -la /` (or the `WRKLNK` equivalent) and see if `/opt` like so:

```
lrwxrwxrwx    1 qsecofr  0                26 Oct  6 2015  opt -> /QOpenSys/opt
```

**Comment by mlitters** [comment]
Yes - that was the problem. It looks like something went wrong with the ADDLNK command in the beginning of my journey and I didn't checked that.
I am so sorry!!!

**Comment by NattyNarwhal** [comment]
It's alright, accidents happen :)
