### ISSUE TITLE
Package libgdiplus and dependencies

### ISSUE THREAD

**Issue by NattyNarwhal** [MonoOni/binarydist#5]
libgdiplus itself is not hard to port; rather, wrangling its chain of dependencies is. Without it, System.Drawing will crash out hard.

## glib

Probably just use Bull's srpm, patch it for anything i 7.1 lacks, and put in it the prefix. Same for libffi, if we use a version dependent. May be even possible just to use binary package unmodified. 

## exiflib, etc.

Likely easy to build or just recycle Bull binary RPM.

**Comment by glrodgers** [comment]
I think I have the dependencies up on our build LPAR now. Autogen completes with a seemingly benign pkg-config message but appears to succeed. CPPFLAGS will need the usual treatment.

**Comment by NattyNarwhal** [comment]
Initial work on libgdiplus AIX tweaks; though nothing WRT packaging yet: https://github.com/mono/libgdiplus/pull/386

**Comment by richardschoen** [comment]
Hey guys, any progress on gdi stuff ? Some of the samples I'm trying to create require gdi and System.Drawing for rendering image and PDF docs.  Happy to test.

**Comment by NattyNarwhal** [comment]
The RPM specfiles are closer to working (much of the dependencies required are already packaged there, though not all) and would be far more sustainable than the current savefile approach; (for things like fontconfig; especially if Rochester gets around to those dependencies before we do) the savefile doesn't have those.

**Comment by NattyNarwhal** [comment]
libgdiplus is packaged, though may not work best for X11. Packaging related stuff is marked in that repository though.
